- model: Desk
  records:
    - name: '01'
    - name: '02'
    - name: '03'
    - name: '05'
    - name: '06'
    - name: '07'
    - name: '08'
    - name: '09'
    - name: 10
    - name: 11
    - name: 12
    - name: 13
    - name: 21
    - name: 22
    - name: 23
    - name: 25
    - name: 26
    - name: 27
    - name: 28
    - name: 29
    - name: 31
    - name: 32
    - name: 33
    - name: 35
    - name: 36
    - name: 37
    - name: 38
    - name: 51
    - name: 52
    - name: 53
    - name: 55
    - name: 56
    - name: 57
    - name: 58
    - name: 59
    - name: 60
    - name: 61
    - name: 外帶 1
    - name: 外帶 2
    - name: 外帶 3
    - name: 外帶 4
    - name: 外帶 5
    - name: 外帶 6
    - name: 外帶 7
    - name: 外帶 8
    - name: 外帶 9

- model: Category
  records:
    - name: 冷盤
    - name: 吃飽飽
    - name: 古早味大鍋煮
    - name: 下飯配酒好夥伴
    - name: 健康蔬菜
    - name: 燒燒ㄟ湯
    - name: 台式三杯
    - name: 現撈嚐鮮
    - name: 幸福鐵板
    - name: 燒烤
    - name: 飲品
    - name: 其他


- model: POS
  records:
    - name: 櫃檯
      ip: 111.70.1.88:12001
    - name: 廚房1
      ip: 111.70.1.87:12001
    - name: 堂口
      ip: 111.70.1.87:12002
      split: True
    - name: 廚房2
      ip: 111.70.1.87:12003
    - name: 客人
      ip: 111.70.1.87:12004
    - name: 
    - name: 
    - name: 
    - name: 
    - name: 


- model: Staff
  records:
    - name: hu
      password: pbkdf2:sha256:150000$ojbCeSi9$e0eb238ff4100062538850fbfd27519a2986669326663f6bafe46c59166b776e
      is_superuser: 1
      
    - name: test
      password: pbkdf2:sha256:150000$FEbhRkQp$19004bdfaea6219d039073453897f9d07ab88fd1ba01976827847c7d1df6aaee

