- model: Desk
  records:
    - name: A1
    - name: A2
    - name: A3
    - name: A4
    - name: A5
    - name: A6
    - name: A7
    - name: A8

- model: Category
  records:
    - name: 冷盤
    - name: 吃飽飽
    - name: 古早味大鍋煮
    - name: 下飯配酒好夥伴
    - name: 健康蔬菜
    - name: 燒燒ㄟ湯
    - name: 台式三杯
    - name: 現撈嚐鮮
    - name: 幸福鐵板
    - name: 燒烤

- model: Product
  records:
    - name: 綜合生魚片
      category_id: 1
      price: 240
      pos_machs: [1,2,4,5]
    - name: 肉臊拌麵
      category_id: 2
      price: 60
      pos_machs: [1,2,4,5]
    - name: 魚皮白菜滷
      price: 180
      category_id: 3
      pos_machs: [1,2,4,5]
    - name: 炒海瓜子
      category_id: 4
      price: 180
      pos_machs: [1,3,4,5]
      available: False
    - name: 皮蛋地瓜葉
      category_id: 5
      price: 160
      pos_machs: [1,3,4,5]
    - name: 麻油藥膳正土羊鍋（配套）
      category_id: 6
      price: 800
      pos_machs: [1,3,4,5]


- model: POS
  records:
    - name: 櫃檯
      ip: 140.113.131.28
    - name: 廚房1
      ip: 140.113.131.26
    - name: 廚房2
      ip: 140.113.131.27
    - name: 堂口
      split: True
    - name: 客人
    - name: 
    - name: 
    - name: 
    - name: 
    - name: 


- model: Staff
  records:
    - name: hu
      password: pbkdf2:sha256:150000$ojbCeSi9$e0eb238ff4100062538850fbfd27519a2986669326663f6bafe46c59166b776e
      is_superuser: 1
      
    - name: test
      password: pbkdf2:sha256:150000$FEbhRkQp$19004bdfaea6219d039073453897f9d07ab88fd1ba01976827847c7d1df6aaee

